### ISSUE TITLE
Parsing yaml to get one account ID for a specific use-case is difficult

### ISSUE THREAD

**Issue by nitrocode** [fwdcloudsec/known_aws_accounts#44]
For example, segmentio has 2 sources and 2 account ids

https://github.com/fwdcloudsec/known_aws_accounts/blob/26925a79d3ac14b09248c105d281df02b2299f90/accounts.yaml#L12-L14

I assume each account id comes from its respective source.

If that's the case, I'd have to figure out which source relates to my use-case, and then get the respective account id. This is a little tricky the way the yaml is structured.

What do you folks think about this format instead?

```yaml
- name: 'SegmentIO'
  purpose:
    s3:
      source: 'https://segment.com/docs/destinations/amazon-s3/'
      account: '107630771604'
    kinesis:
      source: 'https://segment.com/docs/destinations/amazon-kinesis/'
      account: '595280932656'
```

or even

```yaml
accounts:
  segmentio:
    name: 'SegmentIO'
    purpose:
      s3:
        source: 'https://segment.com/docs/destinations/amazon-s3/'
        account: '107630771604'
      kinesis:
        source: 'https://segment.com/docs/destinations/amazon-kinesis/'
        account: '595280932656'
```

Now I can do something like this

```python
>>> external_accounts["segmentio"]["purpose"]["s3"]["account"]
'107630771604'
```
